### ISSUE TITLE
리드미 파일 업데이트하기

### ISSUE THREAD

**Issue by kkweon** [ultimate-go-korean/translation#1]
소개
기여 방밥

파일에 대한 설명 예를 들면 Table of contents 는 어떠하고

 어떠 어떠한 챕터의 번역 파일명은 어떠 어떠한 것으로 한다 .

일단 생각나는 건 이렇게 세 가지 정도 있습니다

**Comment by nicewook** [comment]
조금 더 세분화해서 어느정도 윤곽이 나오는 데로 리드미 업데이트 하겠습니다.
말씀대로 Git, GitHub 익숙치 않은 분들도 많으시니 온라인 오리엔테이션을 통해 잘 정리해보려 합니다.

**Comment by kkweon** [comment]
> 1. Make folder for each translation assignment
폴더명이 애매하네요. 5-20 폴더명으로 짐작하기로는 페이지수로 만드신것 같은데 그 안의 파일명은 또 README.md 로 하구요.

**Comment by nicewook** [comment]
좋은 대안이 있을까요?
1. assignment.md 에 담당자를 할당하면 담당자는 자신의 범위를 알고 있고, 
2. 페이지수이다 보니 정렬도 되는 장점이 있다 싶습니다.

README.md 의 경우는 
1. 세분화된 폴더의 README.md 가 있는 경우를 보았던 것 같고
2. 말씀대로 폴더명에서 부족한 정보를 폴더별 README.md 로 보완하려 했습니다.

**Comment by kkweon** [comment]
아니요 지금은 리드미에만 적혀 있으면 될 것 같습니다.

**Comment by nicewook** [comment]
1차적 업데이트는 완료하였습니다.
