### ISSUE TITLE
GitBook(legacy), Pandoc 등을 이용한 결과물 웹 서비스

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#13]
범위로 나눈 폴더별로 한글 번역이 완료되었을때에 

1. 각각의 .md 파일을 자동으로 적절히 합치고 나누는 1차 가공을 한 다음
2. 웹 서비스에 적합한 포맷으로 변환한 다음
3. 서비스할 수 있어야 한다.

**Comment by kkweon** [comment]
- GitBook 은 아얘 구버전 노드에서밖에 안돌아거서 포기 (https://github.com/GitbookIO/gitbook-cli/issues/110)


- Pandoc 은 스타일링 추가하면 쓸만할것 같습니다 (https://ultimate-go-korean.github.io/translation/)
    - 추가로 헤딩이 이상한게 보이네요. 원래 모든 챕터가 Language Mechanics  안에 들어가야 되는데 그렇지 못하네요. 마크다운 파일 한번 다시 돌아야 될 것 같습니다.

<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/2981167/95419268-258a6e80-08ee-11eb-897d-a626e682427c.png"></td>

<td><img src="https://user-images.githubusercontent.com/2981167/95419286-2e7b4000-08ee-11eb-9cac-b2270937c2d7.png"></td>
</tr>

<tr>
<td>Markdown 에서 생성된 HTML</td>
<td>PDF 책 원본</td>
</tr>
</table>

**Comment by kkweon** [comment]
헤더는 문제가 아니었습니다. 저자가 볼드체를 잘못 표기했네요.

**Comment by nicewook** [comment]
아~ 이거 말씀하시는 것이었군요.

**Comment by nicewook** [comment]
덕분에 관련된 녀석들을 둘러봤는데 이런 녀석도 있더라구요. 
혹시 아시던 녀석인가요? https://docsify.js.org/#/quickstart

**Comment by kkweon** [comment]
네 그냥 간단한 doc 만들어주는거라서 판독이 훨씬 낫습니다. 지금은 제가 CSS를 안넣어서 못생겨 그런거구요.

**Comment by nicewook** [comment]
그렇군요. 저는 가능하면 prev, next 버튼을 넣어서 좀 이동하게 하거나, 사이드바가 있었으면 했거든요. 
감사합니다.

**Comment by kkweon** [comment]
사이드바는 가능할것 같은데

말씀하시는 바는 저번에 논의한 대로 현재 구조가 싱글 파일로만 가능합니다.

말씀하신 이전페이지 다음페이지 같은 경우는 1챕터 1페이지 이렇게 구분이 되어야 하기 때문에 구조를 크게 손 봐야 됩니다. 파일을 챕터별로 나누고 헤더도 마찬가지구요.

**Comment by nicewook** [comment]
이렇게 하는게 힘들까요? 스크립트나 프로그램하나 이거 전용으로 만들면 가능할 것도 같아서요.

1) 여러 .md 파일을 순서대로 하나의 큰 파일로 만든다.
2) 이것들을 다시 우리가 원하는 크기나 범위별로 나누고 별개의 .md 파일로 만든다
3) 말씀대로 pandoc 으로 서비스한다.
