### ISSUE TITLE
기여하시는 분들의 참여도를 표시하는 가장 좋은 방법은 무엇일까요?

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#14]
어떤 보상이나 혜택이 보장되는 것은 아니지만 가능한 모든 기여의 정도를 보여주면 좋겠습니다. 
대시보드 같이 보여주면 더 좋겠네요. 

- 코드 줄수
- 리뷰 횟수, 수정요청
- 체류 시간
- 문서 작성
- 기타 등등

**Comment by TangoEnSkai** [comment]
코드 줄수나 이런 횟수로 가다보면 크게 의미는 없을 수 있을 것 같습니다. 
그러면 저는 무조건 길게 작성할 것 같아요 :D (농담입니다.)

물리적인 분량보다는 의미 단위로 해석되어지는게 중요한 것 같습니다. 
각 챕터에 대한 번역자와 리뷰어 표시 정도만 있어도 좋지 않을까요?

**Comment by nicewook** [comment]
따로 보상이 없는데 그렇게 까지 하실까 싶어요. 하하
저는 자동으로 저런 요소들을 추출해서 각자의 기여도를 시각화해 보여주었으면 하는데 딱 맞는건 없네요

**Comment by TangoEnSkai** [comment]
개인적인 생각이지만요, 특별하게 표시하고 시각화 하는것 보다 서문에 좋은 글 하나로 여러분들의 기여와 활동, 그리고 특별히 크게 도움 주신 분들에 대한 감사의 메시지 정도도 괜찮지 않을까 싶습니다. 

기여도의 시각화를 약간 오락의 의미로는 재미있을 것 같긴 하지만 뭔가 개인적으로는 "경쟁" 이나 "순위" 같은 것이 있는 것 보다 다 같이 팀의 마인드로 함께 만들어 나가는게 좋지 않을까 싶습니다. 왜냐하면 저는 여기 계시는 모든 분들의 기여도가 같을 것이라고 생각하기 때문입니다. 물론 팀으로서 말이에요 👍 

개인주의 보다는 UDT마인드 처럼요 (cc: @kkweon 😄 )

**Comment by nicewook** [comment]
`그 분` 을 소환하시면 또 짤방 올라옵니다. 🤣

**Comment by nicewook** [comment]
`서문에 좋은 글 하나로 여러분들의 기여와 활동, 그리고 특별히 크게 도움 주신 분들에 대한 감사의 메시지 정도도 괜찮지 않을까 싶습니다.` 
를 넣어두도록 하겠습니다.

**Comment by nicewook** [comment]
기록으로 남겨둡니다. 기여에 대한 감사보다 함께한 분들의 의미로 남겨두고 싶습니다. 
즉, 누군가가 메인이고, 다른 분들이 도와주시는 것이 아니라, `하나의 팀` 으로서 하나의 결과물을 만들어내는 것입니다.

**Comment by nicewook** [comment]
기여하시는 분들 명단을 README.md 에 올려두었습니다.
