### ISSUE TITLE
마크다운 포매터 Prettier 추가 여부

### ISSUE THREAD

**Issue by kkweon** [ultimate-go-korean/translation#17]
각자에게 맡기는 걸로 할까요?

추가할 경우 Node로 벤더락 걸리게 됩니다.

**Comment by nicewook** [comment]
벤더락의 의미가 무엇인지 모릅니다. 특정 툴에 의존하게 되고 번거로운 추가작업이 하나라도 추가된다는 의미일까요?

저는 VSCode 확장프로그램을 따르고는 있는데 필요성을 느끼고 있었습니다. 저는 했으면 하는데 경모님의 판단에 따르겠습니다.

**Comment by kkweon** [comment]
새로운 파일들이 생기게 되고 다 각자 NodeJS 가 설치되어야 합니다. 
저희 블로그 생각하시면 될 것 같습니다. npm 이 리포에 들어오게 됩니당.

**Comment by nicewook** [comment]
그정도는 감당할 비용같습니다. 진행을 해주시면 감사할 따름입니다. 

1. 저도 배워두고 싶네요
2. VSCode 확장프로그램과는 좀 다를지 궁금하네요
