### ISSUE TITLE
다이어그램 처리 방법

### ISSUE THREAD

**Issue by kkweon** [ultimate-go-korean/translation#2]
p.80 에서 다음과 같은 다이어그램이 등장합니다.

![image](https://user-images.githubusercontent.com/2981167/94984942-87219600-0506-11eb-9c1a-a3e432be8fd4.png)

1. 스크릿샷 캡쳐해서 영어 그대로 사용한다.
2. 최대한 비슷한걸 만든다.

어떤게 좋을까요

**Comment by nicewook** [comment]
저도 조금 갈등인데 Words 로 바꾸니 저걸 추출할 수 있더라구요. 
일일이 저자랑 이야기하려니 번거로워서 그걸 일단 가져다 쓴 다음에 저자가 리뷰하면서 의견을 주거나 그때 이야기하려 생각합니다. 이걸 챙기려다가 속도가 안날거 같아서요

**Comment by nicewook** [comment]
이견이 없으시면 일단은 추출한 이미지들을 diagram 이라는 sub folder 를 만들어서 넣어두겠습니다.

**Comment by nicewook** [comment]
./diagrams 디렉토리에 이미지 파일들을 올려두었습니다.
