### ISSUE TITLE
마크다운 헤더 중간에 밀림

### ISSUE THREAD

**Issue by kkweon** [ultimate-go-korean/translation#21]
마크다운 헤더가 Software Design 65 이후부터 한칸 덜 밀렸습니다. 

자세한 정보는 #13 에서 확인

**Comment by kkweon** [comment]
아닙니다 보니까 착각했군요

**Comment by nicewook** [comment]
¯\_(ツ)_/¯

**Comment by kkweon** [comment]
왜 저자는 Language Mechanics 는 bold 체를 사용하고 Software Design 는 볼드체를 안해서 헷갈리게 한걸까요..

**Comment by nicewook** [comment]
전반적으로 완벽히 프로페셔널한 저자는 아니라서 그런게 아닌가 싶은 부분이 있었습니다. 
저는 저자가 들었다는 빌 케네디 코스도 궁금하더군요.
