### ISSUE TITLE
커밋 컨벤션 

### ISSUE THREAD

**Issue by TangoEnSkai** [ultimate-go-korean/translation#24]
따로 있나요? e.g. [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/)

그냥 편하게 하면 될까요?

**Comment by nicewook** [comment]
번역이다 보니 강력한 제약까지는 필요없을듯도 합니다. 
하지만 최소한의 제약을 걸어두고 가이드를 주신다면 다들 공부가 되겠습니다.

**Comment by TangoEnSkai** [comment]
@nicewook 그럼 저는 naive한 conventional commit을 써 보도록 하겠습니다. 
다들 아시는 방법이겠지만 평소 하는대로 하겠습니다 :D 답변 감사합니다.

**Comment by nicewook** [comment]
@TangoEnSkai 님이 조금만 나이브하게 커밋컨벤션 정리해서 채널에 공유해주시면 다들 공부가 될 것 같습니다. 다함께 컨벤션을 맞추는 경험. :-)
