### ISSUE TITLE
코드의 indent 논의 - resolved by 1차 미션 문서 (4 indent)

### ISSUE THREAD

**Issue by davinnovation** [ultimate-go-korean/translation#28]
현재 올려주시는 PR들 및 Submit된 PR들의 go 코드를 보면 indent가 4 혹은 2로 혼재되어 있는 상황입니다.

결정해주실 분 있을까요? 혹은 혼재된 상태로 넘어갈까요?

=> indent 4 통일로 결정되었습니다.

**Comment by davinnovation** [comment]
만약 통일이라면, 개인적으로 2 indent에 투표 하나 던집니다!

**Comment by juunini** [comment]
저도 2indent에 한표 추가합니다 :)

**Comment by davinnovation** [comment]
헉 slack을 보니 `2) 코드내의 들여쓰기가 안맞는 경우가 있습니다. 스페이스 4개로 통일하여 맞추세요`로 이미 결정되어 있었습니다! @juunini 
다른 분들도 참고하실 수 있도록 issue에 남겨두겠습니다.

**Comment by nicewook** [comment]
저도 2를 쓰긴 하지만 원문에서는 4를 쓰고 있기도 하고 책이다 보니 시인성이 중요한 측면이라 4로 하였습니다. 
좋은 이슈 올려주셔서 감사합니다.

**Comment by juunini** [comment]
이미 4 indent 였군요! 감사합니다

**Comment by TangoEnSkai** [comment]
저도 2를 선호합니다만 어느쪽으로 해도 문제는 안될 것 같습니다. 
오랜만에 탭 대신 스페이스를 쓰면 되니깐요.

**Comment by TangoEnSkai** [comment]
> => indent 4 통일로 결정되었습니다.

issue 를 닫으셔도 되지 않을까 싶네요! 좋은 토론 감사합니다.
