### ISSUE TITLE
역자주와 역자 예제를 넣는 좋은 방법이 있을까요? 

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#34]
저자와 이메일을 나누며 코드 배치에 대해서는 어느 정도 양해를 받았습니다. 

![image](https://user-images.githubusercontent.com/6977358/95643992-1e31b380-0aee-11eb-8dc8-69883f7e66ed.png)

예를 들어
1) println() 대신 fmt.Println() 을 쓰기
2) 너무 잘게 쪼개진 code block 을 하나로 뭉치기
3) 저자가 말하고자 하는 바는 유지하면서, 매끄럽게 의역하기 

더해서 `의역`, `역자주`, `역자 예제`도 넣을 수 있으면 좋겠다 생각했습니다. 
1) 역자의 생각을 밝히거나 보충하기
2) 역자가 생각하기에 이해를 더 도울 수 있다고 생각하는 예제 더하기

이들을 원문과 구분할 수 있는 좋은 방법이 있을까요?

**Comment by kkweon** [comment]
우선은 footnote로 가시지요.
깃허브만 지원 안되고 커먼 마크 스펙이라서 Pandoc 변환 할때 자동으로 됩니다.

**Comment by nicewook** [comment]
그랬군요. 깃헙이 왜 지원을 안했을까 되려 궁금하군요. 역자 코드는 일단 두고 역자주는 이걸 활용해야겠습니다

**Comment by nicewook** [comment]
![image](https://user-images.githubusercontent.com/6977358/95653812-64ab0080-0b36-11eb-8621-25a0154c1b3e.png)

**Comment by juunini** [comment]
footnote 좋군요!

**Comment by nicewook** [comment]
Wiki 에 일단 정리해두었습니다
[[역자주는 각주(footnote)를 이용한다]]
