### ISSUE TITLE
CI check for Prettier is counter-productive

### ISSUE THREAD

**Issue by TangoEnSkai** [ultimate-go-korean/translation#37]
영문을 옮겨오고 번역하는 전 과정에서 체크해야 할 사항인지 궁금합니다. 
원본 이동과 초벌 번역에서까지 필요하지 않으면 disable 하는게 어떨까 제안합니다. 

고견 부탁드립니다. 

example output: 

```
Run npm run format:check

> ultimate-go-korean@1.0.0 format:check /home/runner/work/translation/translation
> prettier --check "**/*.{js,json,html,css,md,yaml,yml}"

Checking formatting...
[warn] 164-173/164-173.md
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ultimate-go-korean@1.0.0 format:check: `prettier --check "**/*.{js,json,html,css,md,yaml,yml}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ultimate-go-korean@1.0.0 format:check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-10-10T17_38_29_385Z-debug.log
Error: Process completed with exit code 1.
```

PTAL these open PRs.

![Screenshot 2020-10-11 at 2 45 02](https://user-images.githubusercontent.com/21152231/95661636-cfc2fa00-0b6b-11eb-92d6-ab40d55e6f3e.png)

```

**Comment by kkweon** [comment]
저희는 단순 복사가 아니라 pdf 내용을 마크다운 화 하고 있는 것인데.

마크다운은 소스코드인데 일관된 스타일이 아니라 자기 마음대로하자는 말씀이신가요? 

예를 들어 각자 다 에디터 설정에 따라 설정이 다릅니다.


```
- 레벨1
  - 레벨2


- 레벨1
    - 레벨2








누구는 문단 사이 노말라이즈 안하고
누구는 뒤에 트레일링 스페이스를 길게 넣구오.     

누구는       이렇게 스페이스를 과도하게 넣을 수 있습니다.
```

**Comment by kkweon** [comment]
그리고 추가적으로 npm install 하시면 프리커밋훅이 설치되어 자동으로 변환 됩니다.

**Comment by TangoEnSkai** [comment]
> 저희는 단순 복사가 아니라 pdf 내용을 마크다운 화 하고 있는 것인데.
> 
> 
> 
> 마크다운은 소스코드로 봐야 되는데
> 
> 
> 
> 일관된 스타일이 아니라 자기 마음대로 하자는 말씀이신가요? 
> 
> 
> 
> 예를 들어 각자 다 에디터 설정에 따라 설정이 다릅니다.
> 
> 
> 
> 
> 
> ```
> 
> - 레벨1
> 
>   - 레벨2
> 
> 
> 
> 
> 
> - 레벨1
> 
>     - 레벨2
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 누구는 문단 사이 노말라이즈 안하고
> 
> 누구는 뒤에 트레일링 스페이스를 길게 넣구오.     
> 
> 마크다운에서 트레일링 스페이스는 유의미 하지요.
> 
> 
> 
> 누구는       이렇게 스페이스를 과도하게 넣을 수 있습니다.
> 
> ```
> 
> 
> 
> 이런 자잘한 양식은 Enforce하지 않으면 리뷰어에게 큰 부담이 되기 때문에 저는 그대로 놔뒀으면 희망하는데 다른 분들의 의견을 듣고 싶습니다.

물론 필요하다고 생각합니다. 

다만 매번 하는게 좋을지 아니면 나중에 일괄 수정하는게 좋을지 고민했습니다.

npm과 해당 라이브러리가 익숙하지 않아서요 필요하다면 숙지하겠습니다. 

개인적인 문제인지 다른분들도 그런지 궁금해서 효율적인 방향으로 가고 싶어 제안 드린 겁니다. 답변 감사합니다!

**Comment by TangoEnSkai** [comment]
> 그리고 추가적으로 npm install 하시면 프리커밋훅이 설치되어 자동으로 변환 됩니다.

찾아보겠습니다.

**Comment by TangoEnSkai** [comment]
각 PR마다 양식을 체크하는게 좋다는 의견에 공감합니다. 
관련 에러는 개인적으로 해결하도록 하겠습니다 .

이슈는 닫겠습니다만 관련 내용해서 의견 있으신 분들은 언제든 공유해 주시기 바랍니다. 
감사합니다.
