### ISSUE TITLE
nit: README.md 와 번역체의 일관성

### ISSUE THREAD

**Issue by TangoEnSkai** [ultimate-go-korean/translation#45]
`한다` 와 `합니다` 와 같이 혼용되고 있는 어투를 일관적으로 일치시키면 어떨지 제안해 봅니다. 
README.md의 서체는 기본적으로 `한다`쪽으로 서술되어 있지만, 현재 번역작업의 어체는 동일하지 않습니다. 

어떻게 생각하시나요?

**Comment by juunini** [comment]
저는 `합니다` 에 한표에요!

**Comment by nicewook** [comment]
> 저는 `합니다` 에 한표에요!

왜냐하면을 넣어주시면 더욱 좋을 것 같습니다. :-)
https://dl4ab.github.io/2020/09/17/lesson-learned-at-bluehole/

**Comment by nicewook** [comment]
`한다` 에 한 표입니다. 왜냐하면

1. 종이지면과 이북 바이트를 아낄 수 있습니다. 
2. 같은 의미를 좀더 간결하게 전달할 수 있습니다.

**Comment by juunini** [comment]
저는 `합니다` 에 한표 입니다.

자서전이나 수필같은 느낌이라면 `한다`가 맞다고 생각하지만, 우리는 지침서(?) 성격의 것을 번역하다보니 `합니다` 쪽이 더 어울린다고 생각합니다.

**Comment by nicewook** [comment]
하지만, 많은 개발서적이 `한다`를 쓰고 있지 않은지요? 라고 반론을 해봅니다.

**Comment by juunini** [comment]
그것도 그렇지요 ㅎㅎ
다른분들 의견도 들어보고 결정해도 괜찮을 것 같아요

**Comment by kkweon** [comment]
> `한다` 에 한 표입니다. 왜냐하면
> 
> 1. 종이지면과 이북 바이트를 아낄 수 있습니다.
> 2. 같은 의미를 좀더 간결하게 전달할 수 있습니다.

저는 이 이유가 좋네요.

**Comment by TangoEnSkai** [comment]
특별한 의견 없습니다만, 현재 README 하나만 수정할지,
지금 합니다 투로 번역된 전체를 다 수정할 지에 대한 비용을 생각해 봐야 할 것 같습니다.

저는 한글 번역은 시작을 아직안해서 개인적으로 둘다 코스트가 0입니다만,
번역이나 한글 문서를 벌써 생산하시고 계신 분들의 의견을 따라가도록 하겠습니다. 

개인적으로는 어느쪽이라도 일관성만 있으면 된다고 생각합니다. 
영국영어나 미국영어 스펠링 일관적으로만 적으면 문제되지 않지만 혼용하면 dissertation 적을 때 리뷰 에서 지적 받는 것 처럼요.

**Comment by TangoEnSkai** [comment]
결론을 짓고 이슈를 닫고 싶은데요, 조언 부탁드립니다.

**Comment by nicewook** [comment]
언급하신 대로 일관성만 있으면 큰 문제는 아니라 생각합니다. 
다만 착한 독재자인 척 하면서 `한다` 로 밀고 나가고 싶은데 금요일 오리엔테이션에서 좀 더 의견을 듣고 진행하겠습니다.

**Comment by nicewook** [comment]
추가 논의 계획이니 제가 닫겠습니다.
