### ISSUE TITLE
번역에 있어서 컨벤션 등등 챙겨야 할 항목들을 논의했으면 합니다.

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#46]
번역에 통일성있는 작업이 필요합니다. 챙겨야 할 부분을 이야기해보고 싶습니다. 좋은 의견이나 제안 부탁드립니다.

예를 들어서 다음과 같은 분류가 가능하겠습니다.

## 어투

- `이다` vs `입니다`
- 번역투를 지양하기 위한 주요 번역투 예시 및 학습 (리뷰를 통해서도 잡아야 합니다)

## 단어 번역

`zero value` 를 예로 들자면

- 제로값, 제로 값, 제로 벨류 등으로 표현하거나 영문 그대로 zero value 로 표현할 수 있습니다.
- 혹은 챕터별, 또는 책에서 처음 쓰일때는 제로 값(zero value) 로 한글, 영어를 병기한 다음에 이후 한글만 쓰는 방법이 있습니다.

## 어투와 단어에 대한 관리 

- 구글 시트를 (이번에 범위 지정할때처럼) 공유하고, 수시로 업데이트하는 방법이 우선 떠오릅니다. 완벽한 정리후에 번역을 하는 것은 지지부진하고, 심지어 불가능하다고 보며, 실제 번역을 해가면서, 이슈나 PR 리뷰시에 논의가 되는 것들 하나씩을 바로바로 업데이트 하도록 합니다. 
- 번역이 애매한 경우는 원문 단어를 그대로 쓰시기 바랍니다. `zero value`라고 그대로 써놓으면 이후 결정이 되고나면 일괄 수정이 가능할 수 있겠습니다.

**Comment by davinnovation** [comment]
1. 어투
`입니다` 선호합니다 :)

2. 단어 번역
zero value (0값) 으로 병기

3. 어투와 단어에 대한 관리
excel을 기본으로 하거나... 혹은 MS 표준을 따르는 건 어떨까요? [web](https://www.microsoft.com/ko-kr/language?rtc=1)

### Reference
- Ubuntu 한국 번역 가이드 - https://wiki.ubuntu.com/UbuntuKoreanTranslators
- Microsoft Docs 한국 번역 가이드 - https://docs.microsoft.com/en-us/globalization/localization/ministyleguides/mini-style-guide-korean
- Microsoft 기술용어 표준 - https://www.microsoft.com/ko-kr/language?rtc=1

**Comment by nicewook** [comment]
1. @davinnovation 님 감사합니다. 가이드도 감사드립니다. :-)
2. 한번 더 `이다` 를 밀어봅니다. 간단히 회사 선반에 있는 녀석들만 들여다 보았습니다.

`이다`: 클린 아키텍처, 읽기좋은 코드가 좋은 코드다, 리팩터링, Concurrency in Go
`입니다`: 칼만 필터는 어렵지 않아. 
-> `입니다` 가 좀더 친근하고 편안한 느낌은 주는데 되려 정보 전달에는 엄밀함이 떨어진다는 인상이 있습니다. 

계속 이야기 나누면서 오는 금요일에 확정하시지요. :-)

**Comment by TangoEnSkai** [comment]
> 이다 입니다

이부분은 #45 와도 연결되고 많은 의견이 공유되었으므로 이쪽에서 정리해도 좋을 것 같습니다.

**Comment by nicewook** [comment]
가벼운 논의는 되었으니 따로 이슈를 열거나, 하나씩 다시 정리해가도록 하겠습니다. 
닫겠습니다.
