### ISSUE TITLE
GitHub 사용법 문의합니다. PR review 시의 "Add single comment" 와 "Start a review" 의 차이는 무엇인가요?

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#47]
아래와 같은 버튼들의 의미를 명확하기 이해하지 못하여 여쭙습니다.
어떨때 어떻게 이용하면 되는지 간략한 가이드나 링크를 부탁드려도 될까요?

![image](https://user-images.githubusercontent.com/6977358/95694552-9d99c100-0c6d-11eb-9b03-565a5ccfefc6.png)

![image](https://user-images.githubusercontent.com/6977358/95694553-9f638480-0c6d-11eb-83ad-7872d60ccee0.png)

**Comment by davinnovation** [comment]
https://zellwk.com/blog/edit-pull-request/#:~:text=If%20you%20click%20on%20add,button%20and%20select%20submit%20review.

add a single comment는 커멘트를 바로 달고, start a review는 review의 종류 ("general feedback", "approve", "request change")를 추가할 수 있는 옵션인 듯 합니다!

**Comment by nicewook** [comment]
감사합니다!

**Comment by nicewook** [comment]
테스트까지는 못해봤지만 
`Add single comment` 는 하나하나 할때마다 바로 올라오고
`Start a review` 를 해주면 이렇게 하나씩 다 comment 나 수정요청을 한 다음에 일괄로 올라가나 봅니다.

**Comment by nicewook** [comment]
이건 제가 간단히 테스트 해보고 공유하겠습니다.

**Comment by kkweon** [comment]
맞습니당 코멘트냐 리뷰+코멘트냐 차이입니다

**Comment by kkweon** [comment]
single comment  여러번 하면 알람 여러번 가니까 리뷰로 해주세요

**Comment by TangoEnSkai** [comment]
질문에 대한 답변이 왼료된 것 같으므로 이슈를 닫도록 하겠습니다. 
토론 감사합니다.

**Comment by assash17** [comment]
Add single comment = comment 1개 달면 끝
Start a review = comment 여러 군데 달고, 확인 눌러야 끝
