### ISSUE TITLE
번역이 매끄럽게 되지 않는 부분, 이해가 되지 않는 부분은 어떻게 논의하는 것이 좋을까요?

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#5]
리뷰는 reviewer 가 보고 이상한 부분을 지적하고, 개선을 제안하는 순서이겠으나
번역 담당자가 번역을 하면서 본인이 이상하다, 어렵다 느낀 부분을 미리 이슈로 만들어서 논의하면 좋겠습니다.

여기 이슈에 올리고 사람들이 보고 처리하는 것이 좋을까요?

**Comment by kkweon** [comment]
좋습니다만 슬랙이 더 나을 것 같네요 휘발성이라서

**Comment by nicewook** [comment]
논의를 기록으로 남기는 것도 의미가 있어보입니다. 

외부에서 번역을 지원하시는 분들을 슬랙으로 유입하는 것도 또 하나의 단계가 되기도 하구요. 아예 이 참에 슬랙으로 모시는 계기로 만들까요? :-)
생뚱맞지만 딥백수 내에서 번역을 하면 커뮤니케이션 측면에서 한결 편하겠다는 생각도 들기는 했습니다.

**Comment by kkweon** [comment]
개인적으로 깃허브를 자주 사용하시는 분이라면 어디에서든 상관없습니다. 저는 깃허브나 슬랙이나 둘다 리얼타임으로 확인하기 때문에요. 그런데 다른 분들도 그럴까 생각이 듭니다.

**Comment by nicewook** [comment]
> 개인적으로 깃허브를 자주 사용하시는 분이라면 어디에서든 상관없습니다. 저는 깃허브나 슬랙이나 둘다 리얼타임으로 확인하기 때문에요. 그런데 다른 분들도 그럴까 생각이 듭니다.

안그래도 이부분이 궁금했습니다. 저도 꽤나 인터넷에 붙어 사는 편인지라 왠만큼 실시간으로 알람을 보는데 깃험은 그렇게 안되더라구요. 어떻게 알람 확인하시나요?

**Comment by kkweon** [comment]
앱이랑 웹이랑 이메일이요. 이정도면 충분한데
보통은 이메일로 봅니다. 핸드폰은 잘 확인하지 않아서.

딱히 특별한 건 없는데 이메일을 잘 안 쓰셔서 그러신 것 같습니다 ㅋㅋ

**Comment by nicewook** [comment]
그렇군요. 언제고 이메일 활용하시는 것도 한번 공유 부탁드립니다. 
어떤 이점이 있으시고 어떻게 녹여내시는지 궁금하네요.

**Comment by TangoEnSkai** [comment]
개인적으로는 깃헙 이슈를 선호하지만요,
휘발성 적인 질문의 성격을 굳이 여기에 남겨도 되지 않아도 될 것 같다는 생각에 동의합니다.
슬랙 채널이 복잡하므로 번역 관련 집중 채널을 하나 만들어도 좋지 않을까 싶습니다. 
(저는 커뮤니티 슬랙은 자주 확인하지는 않습니다만 만약 필요로 한다면 자주 번역 관련 글은 체크할 수 있도록 하겠습니다.)

tmp channel 을 만들고 번역질문 만 올리는것은 어떤가요? 현재 채널은 봇이 알림을 주고 있어서 메시지를 놓쳐버릴 수 있는 경우가 있기 때문입니다.

**Comment by nicewook** [comment]
@TangoEnSkai 좋은 제안이십니다. 너무 체크할 것들이 많아지려나 싶은 우려도 되지만 충분히 시도해볼만 한듯 합니다.
