### ISSUE TITLE
[TODO] Translation needed for Patterns

### ISSUE THREAD

**Issue by TangoEnSkai** [ultimate-go-korean/translation#50]
## WHAT

- translation for the chapter, Patterns
- translate each sub-section into Korean

## WHY

- we have added the original book's contents in markdown format at the 1st phase of this project
- now, as a 2nd phase of the project, we would like to translate these contexts into Korean

## TODO

- Patterns / Context
  - [x] Store and retrieve values from a context #52 
  - [x] WithCancel #53 
  - [x] WithDeadline #87 
  - [x] WithTimeout #88 
  - [x] Request/Response #100

## Note

- [x] 2nd mission: finish korean translation 1/3 by #52 #53

**Comment by nicewook** [comment]
현업에서도 이렇게 이슈를 만들고 일을 하시나요? 
다르다면 마크님의 워크 플로우가 궁금하네요. 👍

**Comment by TangoEnSkai** [comment]
@nicewook FYI, the second mission has been completed as 1/3 of the translation work has been finished by #52 #53 .

**Comment by TangoEnSkai** [comment]
> 현업에서도 이렇게 이슈를 만들고 일을 하시나요?
> 다르다면 마크님의 워크 플로우가 궁금하네요. 👍

그떄그떄 다릅니다. 마이크로디시션에 입각해서 일을 하기 떄문에, 
팀이나 개인이 담당하는 프로젝트에서 가장 효율적인 방법으로 합니다. 

저는 개인적으로 큰 뷰가 없으면 일을 하지 못합니다. 그래서 전체적인 그림을 그려두고 태스크를 아토믹하게 브레이크 다운을 한 상태에서
하나씩 하나씩 해 나갑니다. 그래야 일하기도 리뷰하기도 편한 것 같습니다. 

또 제가 한 일은 간단하게 정리나 기록으로 남겨둡니다. 
프로젝트의 경우 로드맵이나 (간트 차트 등) 툴을 사용해서 대략 타임라인과 스케쥴을 잡고 있구요,
각각의 테스크는 하나의 이슈나 여러개의 이슈로 정의해서 묶어 둡니다. 

왜냐하면
- 스스로 일 하는데 단위시간별 레트로스펙티브 하기가 편합니다. 
- 나중에 온보딩 할 때 다른 멤버에게 도움이 됩니다. 
- 이후 다른 주니어나 팀원에게 비슷하거나 유사한 일을 할 때 공부와 도움이 됩니다.  (본인 포함)

**Comment by TangoEnSkai** [comment]
@nicewook https://github.com/ultimate-go-korean/translation/pull/52#discussion_r506992681 관련해서 TODO 리스트에 전체 번역 재방문 추가했습니다. 그 때 다시 한번 함꼐 검토해 주시면 감사하겠습니다.

**Comment by TangoEnSkai** [comment]
initial translation has been reviewed and merged to the main, 
thus i close this issue.
