### ISSUE TITLE
번역의 통일성을 위한 작업은 어떻게 하는 것이 좋을까요?

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#6]
지금 `5-20` 페이지 번역을 하면서도 통일성이 자주 흔들림을 느낍니다. 

- zero value 는 원어 그대로 쓰고 있습니다.
- size 는 크기라고 번역하고 있습니다.
- Goroutine 은 고루틴이라고 쓰고 있습니다.

어떻게 쓰는 것이 좋은지, 또한 이런 용어/단어들의 사용을 여러 번역 담당자들이 일관되게 유지하기 위해서는 어떤 방법이 좋을까요?

**Comment by kkweon** [comment]
어렵습니다. Proofread 하는 수밖에 없지요.

일단 몇가지 방법들로 

0. shared dictionary 를 만드는 방법이 있습니다 스프레드시트에 적는 것처럼요.
1. 영어 원문을 마크다운으로 먼저 체크인한다음에 PR 로 한글 번역이 리뷰되도록 해야 된다고 생각합니다. 마음대로 커밋하는게 아니라요.

**Comment by nicewook** [comment]
0. 깃헙 레포의 WiKi 를 이용하는 것은 어떨까요? 별도의 Tool 로의 context switching 이 일어나지 않는건 장점이다 싶습니다.
1. 일이 두 배로 늘어나는 단점이 있겠습니다. 말씀드린대로 맡게되는 분량이 최대 20 page 로 적기 때문에 옆에 PDF 를 띄워놓고 할 수 있겠다 싶습니다. 더해서 저는 의역을 좀 많이 하려는 중입니다. 말씀하신 부분도 고민해보겠습니다. @@

**Comment by snowmerak** [comment]
@kkweon 님처럼 dictionary를 만드는 게 좋다고 생각합니다. 
또 의역같은 부분은 주석 처리를 활용하는 것은 어떤가요??

**Comment by nicewook** [comment]
1. WiKi 보다는 구글시트 하나를 링크걸어 두는게 낫다는 말씀으로 이해해봅니다. 
2. 의역은 역자주를 말씀하시는 건가요? 조금 번역해봤는데 원저자의 문장이 조금 어렵거나 헷갈리는 부분도 있어서 큰 틀에서 문제가 되지 않고 뜻만 잘 전달되면 의역도 괜찮다 싶습니다. 역자주나 추가적인 역자의 코멘트와 코드도 넣고 싶은데 방법이 있으면 좋겠습니다.
