### ISSUE TITLE
11 page 번역문의

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#7]
11 page 의 번역이 매끄럽지 않네요. 어떻게 이해하고 번역하면 될까요? 

Zero value enables us to initialize every stack frame that we take. Stacks are
self cleaning. We clean our stack on the way down. Every time we make a function,
zero value initialization cleans the stack frame. We leave that memory on the way
up because we don't know if we would need that again.

**Comment by kkweon** [comment]
0 값은 우리가 필요한 모든 스택 영역에서 초기화를 해줍니다. 스택 영역은 계산을 마치고 저절로 할당된 메모리를 해제합니다.  스택에 쌓인 것들을 위에서부터 하나하나 제거해 나갑니다. 매번 함수를 생성할 때마다 영값이 스택 영역을 청소해 줍니다. 스택 영역에 값이 쌓이는 동안은 이 값이 언제 사용 될지 모르기 때문에 유지 되어야 합니다

**Comment by kkweon** [comment]
이제 여기서 좀 더 매끄럽게 연결 해 주면 될 거 같아요

**Comment by nicewook** [comment]
말씀을 들어도 충분히 소화가 안되네요. 맨 아래 문장에 목에 걸립니다.

` We leave that memory on the wayup because we don't know if we would need that again.`

**Comment by kkweon** [comment]
값을 층층이 쌓아 올리는게 스택이잖아요.
바닥에 있는 값을 빼고 다시 넣는게 아니라 적어도 스코프 안에서는 층층이 쌓아 올리는 거죠. 언제 다시 필요할지 모르니까요.

코드로 얘기하자면 변수가 첫 번째 줄에 선언 되었으면 그 함수의 스코프가 끝날 때까지 첫 번째 변수의 값이 계속 스택에서 유지가 되겠죠

**Comment by nicewook** [comment]
함수들이 연달하 호출되고 리턴될때의 상황을 이야기하는 것이지요? 
제가 어디선가 헷갈렸나 봅니다. 감사합니다.
