### ISSUE TITLE
번역: value 라는 단어가 껄끄럽습니다

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#8]
11 페이지의 value 라는 단어가 맞는 건가요? variable 이라고 표현하는 게 맞지 않나요? 
value 가 유사하게 쓰이는 경우가 많은데 오히려 제가 잘못 이해하는 것일까요?

Declare variable of type int with a value of 10. This value is put on a stack with
a value of 10.

// To get the address of a value, we use &.

**Comment by kkweon** [comment]
값이 맞는 것 같습니다

**Comment by kkweon** [comment]
아니 이제 보니까 두 번째 단어 말씀이시군요 잘못된 것 같습니다

**Comment by nicewook** [comment]
네, 아래 두 부분입니다. 저자가 종종 변수(variable)를 써야할 부분에 값(value)라고 쓴다는 느낌입니다.

Declare variable of type int with a value of 10. This `value` is put on a stack with
a value of 10.

// To get the address of a `value,` we use &.

**Comment by kkweon** [comment]
굳이 한글로 쓰자면 이 값은 10이라는 값으로 스택에 들어 갑니다. 막상 틀린 건 아닌 거 같은데 오해의 소지가 확실해 있는 거 같습니다
