### ISSUE TITLE
번역: 11페이지 We are using pointer semantics.

### ISSUE THREAD

**Issue by nicewook** [ultimate-go-korean/translation#9]

**Comment by kkweon** [comment]
그냥 포인트를 사용합니다라고 하면 될 것 같습니다. 
번역에서 중요한게 단어대 단어를 치환하지 않는게 중요합니다.

**Comment by nicewook** [comment]
value semantics 라는 표현도 이어 나와서 어딘가 좀 더 들여다봐야 할 표현인가 싶었습니다. 감사합니다.
